# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.18"
  src = "src"
  test = "test"

[profile.default.fuzz]
  max_test_rejects = 100_000
  runs = 1_000

[profile.ci]
  fuzz = { runs = 10_000 }

[etherscan]
  ethereum = { key = "${ETHERSCAN_API_KEY}" }
  goerli = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
  localhost = "http://localhost:8545"
  goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
