# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  fs_permissions = [{ access = "read", path = "./optimized-out" }]
  gas_reports = ["PRBProxy", "PRBProxyFactory", "PRBProxyRegistry"]
  ignored_error_codes = [
    5159, # ignore selfdestruct warning
  ]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.18"
  src = "src"
  test = "test"

[profile.default.fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 1_000

[profile.ci]
  fuzz = { runs = 10_000 }

# Speed up compilation and tests during development
[profile.lite]
  fuzz = { runs = 50 }
  optimizer = false

# Compile only the production code with IR
[profile.optimized]
  out = "optimized-out"
  test = "src"
  via_ir = true

# Test the optimized contracts without re-compiling them
[profile.test-optimized]
  fuzz = { runs = 5_000 }
  src = "test"
  verbosity = 4

[etherscan]
  ethereum = { key = "${ETHERSCAN_API_KEY}" }
  goerli = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
  localhost = "http://localhost:8545"
  goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
