# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.17"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }

[rpc_endpoints]
localhost="http://localhost:8545"
goerli="https://goerli.infura.io/v3/${INFURA_API_KEY}"
