name: Deployment Request
description: Request to deploy PRBProxy on a new chain.
labels: ["Deployment Request"]
assignees:
  - mds1
body:
  - type: input
    id: chain-name
    attributes:
      label: Chain Name
      description: What is the name of the chain?
      placeholder: "For example: Arbitrum"
    validations:
      required: true

  - type: input
    id: chain-id
    attributes:
      label: Chain ID
      description: What is the Chain ID?
      placeholder: "For example: 42161"
    validations:
      required: true

  - type: input
    id: rpc-url
    attributes:
      label: RPC URL
      description: What is the RPC URL for the chain?
      placeholder: "For example: https://arbitrum-one.publicnode.com"
    validations:
      required: true

  - type: input
    id: block-explorer-url
    attributes:
      label: Block Explorer URL
      description: What is the URL of the block explorer for the chain?
      placeholder: "For example: https://arbiscan.io"
    validations:
      required: true

  - type: dropdown
    id: deployment-funds
    attributes:
      label: Deployment Funds
      description:
        Have you sent deployment funds to the deployer account (0x3Afb8fEDaC6429E2165E84CC43EeA7e42e6440fF)? Doing so is
        greatly appreciated and will reduce time to deployment!
      options:
        - "Yes"
        - "No"
    validations:
      required: true
